import { test, expect } from '@playwright/test'

test('platform service destinations are read only and AI settings save and reload', async ({ page }) => {
  await page.goto('/admin/login')
  await page.locator('input[autocomplete="username"]').fill('admin')
  await page.locator('input[autocomplete="current-password"]').fill('12345678')
  await page.locator('button[type="submit"]').click()
  await expect(page).toHaveURL(/\/admin\/?$/)
  await page.goto('/admin/settings')
  await page.getByRole('tab', { name: 'AI 与语音' }).click()
  const endpoint = page.locator('input#agent_url')
  await expect(endpoint).toHaveAttribute('readonly', '')
  const original = await page.locator('input#llm_model').inputValue()
  await page.locator('input#llm_model').fill('synthetic-regression-model')
  const saved = page.waitForResponse(r => r.url().includes('/api/v1/admin/settings/ai') && r.request().method() === 'PUT')
  await page.locator('.ant-tabs-tabpane-active button[type="submit"]').click()
  expect((await saved).ok()).toBeTruthy()
  await page.reload()
  await page.getByRole('tab', { name: 'AI 与语音' }).click()
  await expect(page.locator('input#llm_model')).toHaveValue('synthetic-regression-model')
  await page.locator('input#llm_model').fill(original)
  await page.locator('.ant-tabs-tabpane-active button[type="submit"]').click()
  await page.getByRole('tab', { name: '短信配置' }).click()
  await expect(page.locator('input#endpoint')).toHaveAttribute('readonly', '')
  await page.screenshot({ path: test.info().outputPath('platform-endpoint.png'), fullPage: true })
  await page.locator('.brand').click()
  await expect(page).toHaveURL(/\/admin\/?$/)
})
