import { test, expect, type Page } from '@playwright/test'

async function login(page: Page, portal: 'admin' | 'agent', username: string) {
  await page.goto(`/${portal}/login`)
  await page.locator('input[autocomplete="username"]').fill(username)
  await page.locator('input[autocomplete="current-password"]').fill('12345678')
  await page.locator('button[type="submit"]').click()
  await expect(page).toHaveURL(new RegExp(`/${portal}/?$`))
}
async function confirm(page: Page) {
  await page.locator('.ant-popconfirm').getByRole('button', { name: /确.*定|Yes|OK/ }).click()
}

test('campaign contact search and paging preserve selections and zero retries', async ({ page }) => {
  const auth = await page.request.post('/api/v1/auth/login', { data: { username: 'admin', password: '12345678' } })
  const headers = { Authorization: `Bearer ${(await auth.json()).access_token}` }
  const suffix = String(Date.now()).slice(-7)
  const oldName = `Fix7Old-${suffix}`
  const oldResponse = await page.request.post('/api/v1/contacts', { headers, data: { phone: `1350${suffix}`, name: oldName, consent_state: 'consented' } })
  expect(oldResponse.ok()).toBeTruthy()
  const old = await oldResponse.json()
  const csv = 'phone,name,consent_state\n' + Array.from({ length: 201 }, (_, i) => `134${suffix}${String(i).padStart(3, '0')},Fix7New-${suffix}-${i},consented`).join('\n')
  const imported = await page.request.post('/api/v1/contacts/import', { headers, multipart: { file: { name: 'synthetic.csv', mimeType: 'text/csv', buffer: Buffer.from(csv) } } })
  expect(imported.ok()).toBeTruthy()
  expect((await imported.json()).created).toBe(201)
  await login(page, 'admin', 'admin')
  await page.goto('/admin/campaigns')
  await page.getByRole('button', { name: /创建任务/ }).click()
  const dialog = page.getByRole('dialog')
  const name = `Fix7Campaign-${suffix}`
  await dialog.getByLabel('名称', { exact: true }).fill(name)
  const customers = dialog.getByLabel('选择客户', { exact: true })
  await customers.click()
  await Promise.all([page.waitForResponse(r => r.url().includes('/api/v1/contacts?page=2&size=200')), page.getByRole('button', { name: '加载更多客户' }).click()])
  await customers.fill(oldName)
  await page.locator('.ant-select-item-option-content').filter({ hasText: oldName }).click()
  await expect(dialog.getByText('已选择 1 位客户')).toBeVisible()
  await customers.fill(`Fix7New-${suffix}-200`)
  await page.locator('.ant-select-item-option-content').filter({ hasText: `Fix7New-${suffix}-200` }).click()
  await customers.press('Escape')
  await expect(dialog.getByText('已选择 2 位客户')).toBeVisible()
  await dialog.getByLabel('重试次数', { exact: true }).fill('0')
  const savedPromise = page.waitForResponse(r => r.url().endsWith('/api/v1/campaigns') && r.request().method() === 'POST')
  await dialog.getByRole('button', { name: /确.*定|OK/ }).click()
  const saved = await (await savedPromise).json()
  expect(saved.contact_ids).toContain(old.id)
  expect(saved.contact_ids).toHaveLength(2)
  expect(saved.retry_limit).toBe(0)
  await expect(dialog).toBeHidden()
  await page.reload()
  const row = page.getByRole('row').filter({ hasText: name })
  await row.getByRole('button', { name: /编\s*辑/ }).click()
  await expect(dialog.getByLabel('重试次数', { exact: true })).toHaveValue('0')
  await expect(dialog.getByText('已选择 2 位客户')).toBeVisible()
  await page.screenshot({ path: test.info().outputPath('saved-campaign.png'), fullPage: true, animations: 'disabled' })
  await expect(dialog.locator('.ant-select-selection-item').filter({ hasText: oldName })).toBeVisible()
  await dialog.getByRole('button', { name: /取.*消|Cancel/ }).click()
  // Only the explicitly isolated fixture may enqueue synthetic calls.
  if (process.env.E2E_FIX7_ISOLATED) {
    await row.getByRole('button', { name: /启\s*动/ }).click(); await confirm(page)
    await row.getByRole('button', { name: /暂\s*停/ }).click()
    await row.getByRole('button', { name: /恢\s*复/ }).click()
    await row.getByRole('button', { name: /停\s*止/ }).click(); await confirm(page)
    await row.getByRole('button', { name: /编\s*辑/ }).click()
    await dialog.locator('.ant-select').filter({ has: page.locator('input#mode') }).click()
    await page.locator('.ant-select-item-option-content').getByText('纯人工', { exact: true }).click()
    await dialog.getByLabel('重试次数', { exact: true }).fill('5')
    await dialog.getByRole('button', { name: /确.*定|OK/ }).click()
    await expect(dialog).toBeHidden()
    await row.getByRole('button', { name: /启\s*动/ }).click(); await confirm(page)
    await expect(row.getByRole('button', { name: /暂\s*停/ })).toBeVisible()
    const calls = await (await page.request.get(`/api/v1/calls?campaign_id=${saved.id}`, { headers })).json()
    expect(calls).toHaveLength(2)
    expect(calls.every((call: { mode: string; max_attempts: number }) => call.mode === 'human_only' && call.max_attempts === 6)).toBeTruthy()
    await row.getByRole('button', { name: /停\s*止/ }).click(); await confirm(page)
  }
  await page.locator('.brand').click()
  await expect(page).toHaveURL(/\/admin\/?$/)
})

test('call pagination requests a different server page and supports returning', async ({ page }) => {
  await login(page, 'agent', '1001@test')
  const requested: number[] = []
  await page.route('**/api/v1/calls?**', route => {
    const number = Number(new URL(route.request().url()).searchParams.get('page'))
    requested.push(number)
    return route.fulfill({ json: Array.from({ length: number === 1 ? 20 : 1 }, (_, i) => ({
      id: `page-${number}-${i}`, phone: `ServerPage${number}Call${i}`, mode: 'human_only', status: 'completed', attempts: 1, max_attempts: 1, created_at: '2026-09-05T00:00:00',
    })) })
  })
  await page.goto('/agent/calls')
  await expect(page.getByRole('cell', { name: 'ServerPage1Call0', exact: true })).toBeVisible()
  await page.getByRole('button', { name: '下一页', exact: true }).click()
  await expect(page.getByRole('cell', { name: 'ServerPage2Call0', exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: '下一页', exact: true })).toBeDisabled()
  await page.getByRole('button', { name: '上一页', exact: true }).click()
  await expect(page.getByRole('cell', { name: 'ServerPage1Call0', exact: true })).toBeVisible()
  expect(requested).toContain(2)
})

test('manual handoff requeues on no answer and can be accepted and ended', async ({ page }) => {
  test.skip(!process.env.E2E_FIX7_ISOLATED, 'requires isolated mock telephony')
  await login(page, 'agent', '1001@test')
  await page.goto('/agent/calls')
  await page.getByRole('button', { name: /发起外呼/ }).click()
  const dialog = page.getByRole('dialog')
  const phone = `139${String(Date.now()).slice(-8)}`
  await dialog.getByLabel('手机号', { exact: true }).fill(phone)
  const createdPromise = page.waitForResponse(r => r.url().endsWith('/api/v1/calls') && r.request().method() === 'POST')
  await dialog.getByRole('button', { name: /确.*定|OK/ }).click()
  const response = await createdPromise
  expect(response.ok()).toBeTruthy()
  const call = await response.json()
  const row = page.getByRole('row').filter({ hasText: phone })
  const transfer = page.waitForResponse(r => r.url().includes(`/calls/${call.id}/handover`) && r.request().method() === 'POST')
  await row.getByRole('button', { name: '转人工', exact: true }).click(); await confirm(page)
  expect((await transfer).ok()).toBeTruthy()
  const unavailable = await page.request.post('/api/v1/webhooks/telephony/status', { data: { call_id: call.id, kind: 'status', payload: { status: 'human_unavailable', attempt: call.attempts, event_id: `e2e-unavailable-${call.id}` } } })
  expect((await unavailable.json()).requeued).toBeTruthy()
  await page.goto('/agent')
  const queueRow = page.locator('.handoff-item').filter({ hasText: phone })
  const accepted = page.waitForResponse(r => r.url().endsWith('/accept') && r.request().method() === 'POST')
  await queueRow.getByRole('button', { name: /接\s*受/ }).click(); await confirm(page)
  expect((await accepted).ok()).toBeTruthy()
  await page.request.post('/api/v1/webhooks/telephony/status', { data: { call_id: call.id, kind: 'status', payload: { status: 'human_connected', attempt: call.attempts, event_id: `e2e-connected-${call.id}` } } })
  await page.goto('/agent/calls')
  await row.getByRole('button', { name: /挂\s*断/ }).click(); await confirm(page)
  await page.request.post('/api/v1/webhooks/telephony/status', { data: { call_id: call.id, kind: 'status', payload: { status: 'completed', attempt: call.attempts, event_id: `e2e-completed-${call.id}` } } })
  await page.getByRole('button', { name: /刷\s*新/ }).click()
  await expect(row.getByRole('button', { name: /挂\s*断/ })).toBeDisabled()
  await row.getByRole('button', { name: /事\s*件/ }).click()
  await expect(page.locator('.ant-drawer')).toBeVisible()
})
