import { expect, test, type Page } from '@playwright/test'
async function login(page: Page, role: 'admin' | 'agent' = 'admin') {
  await page.goto(`/${role}/login`)
  await page.locator('input[autocomplete="username"]').fill(role === 'admin' ? 'admin' : '1001@test')
  await page.locator('input[autocomplete="current-password"]').fill('12345678')
  await page.locator('button[type="submit"]').click()
  await expect(page).toHaveURL(new RegExp(`/${role}/?$`))
  return { Authorization: `Bearer ${await page.evaluate(() => sessionStorage.getItem('ai-platform-access-token'))}` }
}
test('business policy saves fields and FAQ, simulates negation and rejects stale publishing', async ({ page, request }) => {
  const headers = await login(page)
  const original = await (await request.get('/api/v1/product/policy', { headers })).json()
  try {
    await page.getByRole('menuitem', { name: '业务交付策略' }).click()
    await expect(page.getByRole('heading', { name: '业务交付策略', level: 2 })).toBeVisible()
    await page.getByLabel('策略名称', { exact: true }).fill('浏览器验收策略')
    await page.getByLabel('全局问答', { exact: true }).fill('{"你们是谁":"我们是客户服务团队。"}')
    await page.getByRole('tab', { name: '信息采集', exact: true }).click()
    await page.getByRole('button', { name: '添加字段', exact: true }).click()
    await page.getByLabel('字段标识', { exact: true }).last().fill('city')
    await page.getByLabel('名称', { exact: true }).last().fill('城市')
    await page.getByLabel('询问话术', { exact: true }).last().fill('您在哪个城市？')
    const saved = page.waitForResponse(r => r.url().endsWith('/product/policy') && r.request().method() === 'POST')
    await page.getByRole('button', { name: '发布策略', exact: true }).click()
    expect((await saved).ok()).toBeTruthy()
    await page.reload()
    await expect(page.getByLabel('策略名称', { exact: true })).toHaveValue('浏览器验收策略')
    await expect(page.getByLabel('全局问答', { exact: true })).toHaveValue(/客户服务团队/)
    await page.getByRole('tab', { name: '信息采集', exact: true }).click()
    await expect(page.getByLabel('字段标识', { exact: true }).last()).toHaveValue('city')
    await page.getByRole('tab', { name: '试跑与版本', exact: true }).click()
    await page.getByLabel('客户对话样例').fill('不用转人工\n我需要你们别再打')
    await page.getByRole('button', { name: '运行对话试跑' }).click()
    await expect(page.getByRole('cell', { name: 'decline_handoff', exact: true })).toBeVisible()
    await expect(page.getByRole('cell', { name: 'stop_contact', exact: true })).toBeVisible()
    expect((await request.post('/api/v1/product/policy', { headers, data: { policy: original.policy, expected_version_id: original.version_id } })).status()).toBe(409)
    await page.screenshot({ path: test.info().outputPath('product-policy.png'), fullPage: true })
    await page.locator('.brand').click()
    await expect(page).toHaveURL(/\/admin\/?$/)
  } finally {
    const current = await (await request.get('/api/v1/product/policy', { headers })).json()
    expect((await request.post('/api/v1/product/policy', { headers, data: { policy: original.policy, expected_version_id: current.version_id } })).ok()).toBeTruthy()
  }
})
test('knowledge and incoming follow-up save, search and complete', async ({ page, request }) => {
  const headers = await login(page)
  await page.goto('/admin/product')
  await page.getByRole('tab', { name: '知识导入与检索测试' }).click()
  const title = `知识验收-${Date.now()}`
  await page.getByLabel('知识标题').fill(title)
  await page.getByLabel('知识出处').fill('测试文档')
  await page.getByLabel('知识正文').fill('车辆评估费用为零，请以实际合同约定为准。')
  const saved = page.waitForResponse(r => r.url().endsWith('/knowledge/import'))
  await page.getByRole('button', { name: '保存知识' }).click()
  expect((await saved).ok()).toBeTruthy()
  await page.getByLabel('检索问题').fill(title)
  await page.getByRole('button', { name: '测试检索' }).click()
  await expect(page.getByRole('cell', { name: title, exact: true })).toBeVisible()
  const event = { event_id: `browser-${Date.now()}`, phone: '13912340001', kind: 'sms_reply', text: '请安排人工回电' }
  expect((await request.post('/api/v1/product/incoming', { headers, data: event })).ok()).toBeTruthy()
  expect((await (await request.post('/api/v1/product/incoming', { headers, data: event })).json()).duplicate).toBeTruthy()
  expect((await request.post('/api/v1/product/incoming', { headers, data: { ...event, text: '冲突内容' } })).status()).toBe(409)
  await page.reload()
  await page.getByRole('tab', { name: '人工跟进', exact: true }).click()
  const row = page.getByRole('row').filter({ hasText: '请安排人工回电' }).first()
  await expect(row).toBeVisible()
  await row.getByRole('button', { name: '标记完成' }).click()
  await expect(row.getByRole('button', { name: '标记完成' })).toBeDisabled()
  await page.reload()
  await page.getByRole('tab', { name: '人工跟进', exact: true }).click()
  await expect(page.getByRole('row').filter({ hasText: '请安排人工回电' }).first()).toContainText('completed')
})
test('agent and anonymous sessions cannot access product administration', async ({ page, request }) => {
  expect((await request.get('/api/v1/product/policy')).status()).toBe(401)
  const headers = await login(page, 'agent')
  expect((await request.get('/api/v1/product/policy', { headers })).status()).toBe(403)
  expect((await request.post('/api/v1/product/incoming', { headers, data: { event_id: 'forbidden', phone: '13912340002', kind: 'sms_reply', text: '测试' } })).status()).toBe(403)
  await page.goto('/admin/product')
  await expect(page).toHaveURL(/\/agent$/)
})

test('seeded appointment can be rescheduled and cancelled from its row', async ({ page, request }) => {
  const headers = await login(page)
  const appointments = await (await request.get('/api/v1/product/appointments', { headers })).json()
  const appointment = appointments.find((row: { request_key: string; state: string }) => row.request_key === 'browser-appointment' && row.state === 'confirmed')
  test.skip(!appointment, 'isolated appointment seed not supplied')
  await page.goto('/admin/product')
  const row = page.getByRole('row').filter({ hasText: appointment.phone }).first()
  const target = await page.evaluate(() => {
    const next = new Date(Date.now() + 48 * 3600 * 1000)
    // 06:00 UTC is 14:00 in the configured Asia/Shanghai business calendar.
    next.setUTCHours(6, 0, 0, 0)
    const local = new Date(next.getTime() - next.getTimezoneOffset() * 60000)
    return local.toISOString().slice(0, 16)
  })
  await row.locator('input[type="datetime-local"]').fill(target)
  const update = page.waitForResponse(r => r.url().includes(`/appointments/${appointment.id}`) && r.request().method() === 'PATCH')
  await row.getByRole('button', { name: '保存时间' }).click()
  expect((await update).ok()).toBeTruthy()
  await page.reload()
  await expect(row).toContainText('confirmed')
  await row.getByRole('button', { name: '取消预约' }).click()
  await page.locator('.ant-popover').getByRole('button', { name: /确\s*定|Yes|OK/ }).click()
  await expect(row).toContainText('cancelled')
  await page.reload()
  await expect(row.getByRole('button', { name: '取消预约' })).toBeDisabled()
})

test('flow editor persists a collection variable and exposes new node types', async ({ page, request }) => {
  const headers = await login(page)
  const name = `采集画布验收-${Date.now()}`
  const created = await request.post('/api/v1/script-templates', { headers, data: { name, content: '测试开场', category: 'test' } })
  expect(created.ok()).toBeTruthy()
  const template = await created.json()
  const version = await (await request.post(`/api/v1/script-templates/${template.id}/flows`, { headers, data: {} })).json()
  const graph = { nodes: [
    { id: 'start', type: 'start', label: '开始', position: { x: 20, y: 30 } },
    { id: 'city', type: 'collect', label: '城市', variable: 'city', prompt: '城市？', position: { x: 250, y: 30 } },
    { id: 'end', type: 'hangup', label: '结束', position: { x: 480, y: 30 } },
  ], edges: [{ id: '1', source: 'start', target: 'city' },{ id: '2', source: 'city', target: 'end' }] }
  expect((await request.put(`/api/v1/script-templates/${template.id}/flows/${version.id}`, { headers, data: { graph } })).ok()).toBeTruthy()
  await page.goto('/admin/scripts')
  await page.locator('.script-card').filter({ hasText: name }).getByRole('button', { name: '话术画布' }).click()
  const dialog = page.getByRole('dialog')
  await expect(dialog.getByRole('button', { name: '采集信息', exact: true })).toBeVisible()
  await expect(dialog.getByRole('button', { name: '设置变量', exact: true })).toBeVisible()
  await expect(dialog.getByRole('button', { name: '条件分支', exact: true })).toBeVisible()
  await dialog.locator('.flow-node-collect').click()
  await dialog.getByLabel('变量名称').fill('customer_city')
  const saved = page.waitForResponse(r => r.url().endsWith(`/flows/${version.id}`) && r.request().method() === 'PUT')
  await dialog.getByRole('button', { name: /保\s*存/, exact: true }).click()
  expect((await saved).ok()).toBeTruthy()
  await page.reload()
  await page.locator('.script-card').filter({ hasText: name }).getByRole('button', { name: '话术画布' }).click()
  await dialog.locator('.flow-node-collect').click()
  await expect(dialog.getByLabel('变量名称')).toHaveValue('customer_city')
  await dialog.getByRole('button', { name: 'Close', exact: true }).click()
  await page.locator('.brand').click()
  await expect(page).toHaveURL(/\/admin\/?$/)
})
